---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # ClusterIssuer so it can issue certificates in istio-system
metadata:
  name: {{ .Release.Namespace }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Release.Namespace }}-ca