---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: Teamspace {{ .Release.Namespace }} CA
  secretName: {{ .Release.Namespace }}-ca
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Never
  duration: 26280h   # ~3y
  renewBefore: 720h  # 30d
  usages:
    - cert sign
    - crl sign
    - digital signature
    - key encipherment
  issuerRef:
    name: teknoir-intermediate-ca
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-wildcard-crt
  namespace: cert-manager
spec:
  secretName: {{ .Release.Namespace }}-wildcard-crt
  issuerRef:
    kind: Issuer
    name: {{ .Release.Namespace }}-ca
  dnsNames:
    - '{{- printf "%s.%s" .Release.Namespace .Values.domain -}}'
    - '{{- printf "*.%s.%s" .Release.Namespace .Values.domain -}}'
  # can't have more than one wildcard, otherwise this error will appear
  # urn:ietf:params:acme:error:rejectedIdentifier: [dns: *.*.demonstrations.teknoir.dev] Error creating new order :: Domain name has more than one wildcard
